<?php

namespace Override\ScrumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantRepository extends EntityRepository
{

	public function findByNonePromotion(){
		return $this->getEntityManager()
            ->createQuery(
                'SELECT e, p FROM OverrideScrumBundle:Promotion p
                	LEFT JOIN p.etudiants e
                '
            )
            ->getResult();
	}

}
