<?php

namespace Override\ScrumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtudiantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudiantRepository extends EntityRepository
{

	public function findAllInPromotion($idPromotion){

		return $this->getEntityManager()
            ->createQuery(
                'SELECT e, p FROM OverrideScrumBundle:Promotion p
                	INNER JOIN p.etudiants e
                	WHERE p.id != :idPromotion
                	GROUP BY e.id
                '
            )
            ->setParameter('idPromotion', $idPromotion)
            ->getResult();
	}

}
