<?php

namespace Override\ScrumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends EntityRepository
{
    public function findBySecretaireFormation($userId)
    {
        return $this->getEntityManager()
                    ->createQuery(
                            'SELECT f
                            FROM OverrideScrumBundle:Formation f
                            INNER JOIN f.secretaireFormation sf
                            INNER JOIN sf.user u
                            WHERE u.id = :secretaireId'
                    )
                    ->setParameter('secretaireId', $userId)
                    ->getResult();
    }
}
