<?php

namespace Override\ScrumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends EntityRepository
{

	public function GetBySecretaireFormation($secretaireId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p, c, f, sf FROM OverrideScrumBundle:Promotion p
                	INNER JOIN p.cursus c
                	INNER JOIN c.formation f
                    INNER JOIN f.secretaireFormation sf
                	WHERE sf.id = :secretaireId
                '
            )
            ->setParameter('secretaireId', $secretaireId)
            ->getResult();
    }


}
