<?php

namespace Override\ScrumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends EntityRepository
{

	public function findBySecretaireFormation($secretaireId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p, c, f, sf FROM OverrideScrumBundle:Promotion p
                	INNER JOIN p.cursus c
                	INNER JOIN c.formation f
                    INNER JOIN f.secretaireFormation sf
                	WHERE sf.id = :secretaireId
                '
            )
            ->setParameter('secretaireId', $secretaireId)
            ->getResult();
    }

    public function findBySecretaireFormationByFormation($secretaireId, $formationId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p, c, f, sf FROM OverrideScrumBundle:Promotion p
                    INNER JOIN p.cursus c
                    INNER JOIN c.formation f
                    INNER JOIN f.secretaireFormation sf
                    WHERE sf.id = :secretaireId
                    AND f.id = :formationId
                '
            )
            ->setParameter('secretaireId', $secretaireId)
            ->setParameter('formationId', $formationId)
            ->getResult();
    }


    public function findByFormation($formationId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p, c, f FROM OverrideScrumBundle:Promotion p
                    INNER JOIN p.cursus c
                    INNER JOIN c.formation f
                    WHERE f.id = :formationId
                '
            )
            ->setParameter('formationId', $formationId)
            ->getResult();

    }


}
