<?php

namespace Override\ScrumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Secretaire_formationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecretaireFormationRepository extends EntityRepository
{
}
