override_scrum_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: OverrideScrumBundle:Default:index }

OverrideScrumBundle:
    resource: "@OverrideScrumBundle/Controller"
    type: annotation