parameters:
#    override_scrum.example.class: Override\ScrumBundle\Example
     override_scrum.db.table_prefix: _scrum_

services:
#    override_scrum.example:
#        class: %override_scrum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     override_scrum.tblprefix_subscriber:
         class: Override\ScrumBundle\Subscriber\TablePrefixSubscriber
         arguments: [%override_scrum.db.table_prefix%]
         tags:
         - { name: doctrine.event_subscriber }