parameters:
#    override_scrum.example.class: Override\ScrumBundle\Example

services:
#    override_scrum.example:
#        class: %override_scrum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
