matiere:
    pattern:  /
    defaults: { _controller: "OverrideScrumBundle:Matiere:index" }

matiere_show:
    pattern:  /{id}/show
    defaults: { _controller: "OverrideScrumBundle:Matiere:show" }

matiere_new:
    pattern:  /new
    defaults: { _controller: "OverrideScrumBundle:Matiere:new" }

matiere_create:
    pattern:  /create
    defaults: { _controller: "OverrideScrumBundle:Matiere:create" }
    requirements: { _method: post }

matiere_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "OverrideScrumBundle:Matiere:edit" }

matiere_update:
    pattern:  /{id}/update
    defaults: { _controller: "OverrideScrumBundle:Matiere:update" }
    requirements: { _method: post|put }

matiere_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "OverrideScrumBundle:Matiere:delete" }
    requirements: { _method: post|delete }

matiere_add_prof:
    pattern:  /{id}
    defaults: { _controller: "OverrideScrumBundle:Matiere:addProf" }
    requirements: { _method: post }