parameters:
#    override_fos_user.example.class: Override\FosUserBundle\Example

services:
#    override_fos_user.example:
#        class: %override_fos_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
